import {
  Workspace,
  User,
  Lead,
  Contact,
  Company,
  Deal,
  Task,
  ActivityTimelineItem,
  ProductService,
  Quote,
  Invoice,
  Expense,
  MarketingCampaign,
  LeadCaptureForm,
  PromotionCoupon,
  Conversation,
  Message,
  AppointmentType,
  Appointment,
  AutomationWorkflow,
  AutomationLog,
  AppNotification,
  AuditLog,
  PlanLimits,
} from '../../../shared/types.ts';

export const PLAN_CONFIGS: Record<string, PlanLimits> = {
  free: {
    name: 'Free Plan',
    priceMonthly: 0,
    priceYearly: 0,
    maxTeamMembers: 1,
    maxContacts: 50,
    maxInvoicesPerMonth: 5,
    maxAutomations: 0, // Automations locked on Free plan
    maxCampaigns: 0,
    aiCreditsMonthly: 15,
    storageGB: 1,
    features: ['Core CRM Contacts & Leads', '1 Appointment Type', 'Quotes & 5 Invoices/mo', 'Unified Inbox (Manual)', 'Community Support'],
  },
  professional: {
    name: 'Professional',
    priceMonthly: 10,
    priceYearly: 96,
    maxTeamMembers: 5,
    maxContacts: 1000,
    maxInvoicesPerMonth: 50,
    maxAutomations: 10, // Unlocked
    maxCampaigns: 5,
    aiCreditsMonthly: 500,
    storageGB: 10,
    features: ['Workflow Automation Engine (10 Workflows)', 'Auto Google Meet Links', 'Unlimited Invoices & Stripe Checkout', 'Marketing Campaigns & Forms', '5 Team Seats with RBAC', '500 AI Gemini Credits'],
  },
  business: {
    name: 'Business Scale',
    priceMonthly: 20,
    priceYearly: 192,
    maxTeamMembers: 15,
    maxContacts: 25000,
    maxInvoicesPerMonth: 500,
    maxAutomations: 100, // Unlocked Advanced
    maxCampaigns: 50,
    aiCreditsMonthly: 2500,
    storageGB: 50,
    features: ['Advanced Automations & Webhooks (100 Workflows)', 'Full Marketing Suite & Promo Coupons', '15 Team Seats', 'Advanced BI & Analytics Reports', '2,500 AI Gemini Credits', 'Priority Queue Processing'],
  },
  enterprise: {
    name: 'Enterprise',
    priceMonthly: 60,
    priceYearly: 576,
    maxTeamMembers: 999,
    maxContacts: 999999,
    maxInvoicesPerMonth: 999999,
    maxAutomations: 999, // Unlocked Unlimited
    maxCampaigns: 999,
    aiCreditsMonthly: 25000,
    storageGB: 500,
    features: ['Unlimited Everything', 'Dedicated Isolated Tenancy', 'Unlimited Workflows & Redis Workers', 'Custom Workspace Branding', 'Dedicated Account Support', '24/7 SLA'],
  },
};

const DEFAULT_WORKSPACE_ID = 'ws-nexus-01';

export class InMemoryDatabase {
  workspaces: Workspace[] = [];
  users: User[] = [];
  leads: Lead[] = [];
  contacts: Contact[] = [];
  companies: Company[] = [];
  deals: Deal[] = [];
  tasks: Task[] = [];
  activityTimeline: ActivityTimelineItem[] = [];
  productsServices: ProductService[] = [];
  quotes: Quote[] = [];
  invoices: Invoice[] = [];
  expenses: Expense[] = [];
  campaigns: MarketingCampaign[] = [];
  leadForms: LeadCaptureForm[] = [];
  coupons: PromotionCoupon[] = [];
  conversations: Conversation[] = [];
  messages: Message[] = [];
  appointmentTypes: AppointmentType[] = [];
  appointments: Appointment[] = [];
  automations: AutomationWorkflow[] = [];
  automationLogs: AutomationLog[] = [];
  notifications: AppNotification[] = [];
  auditLogs: AuditLog[] = [];

  constructor() {
    this.seedInitialData();
  }

  seedInitialData() {
    // 1. Workspaces
    this.workspaces = [
      {
        id: DEFAULT_WORKSPACE_ID,
        name: 'Apex Digital Solutions',
        slug: 'apex-digital',
        owner_id: 'usr-owner-01',
        currency: 'USD',
        timezone: 'America/New_York',
        industry: 'B2B Consulting & Tech Services',
        company_email: 'hello@apexdigital.io',
        company_phone: '+1 (555) 234-5678',
        company_website: 'https://apexdigital.io',
        company_address: '742 Evergreen Blvd, Suite 400, New York, NY 10001',
        tax_id: 'US-883920194',
        subscription_plan: 'professional',
        subscription_status: 'active',
        created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
      },
      {
        id: 'ws-nexus-02',
        name: 'Vanguard Retail Co.',
        slug: 'vanguard-retail',
        owner_id: 'usr-owner-01',
        currency: 'USD',
        timezone: 'America/Los_Angeles',
        industry: 'Retail & Commerce',
        company_email: 'contact@vanguardretail.com',
        subscription_plan: 'starter',
        subscription_status: 'active',
        created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
      }
    ];

    // 2. Users & Team
    this.users = [
      {
        id: 'usr-owner-01',
        email: 'alex.rivera@apexdigital.io',
        name: 'Alex Rivera',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        phone: '+1 (555) 301-4499',
        job_title: 'Chief Executive Officer & Founder',
        role: 'owner',
        workspace_id: DEFAULT_WORKSPACE_ID,
        created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
      },
      {
        id: 'usr-admin-02',
        email: 'sarah.chen@apexdigital.io',
        name: 'Sarah Chen',
        avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
        phone: '+1 (555) 782-1923',
        job_title: 'Head of Operations',
        role: 'admin',
        workspace_id: DEFAULT_WORKSPACE_ID,
        created_at: new Date(Date.now() - 80 * 86400000).toISOString(),
      },
      {
        id: 'usr-sales-03',
        email: 'marcus.vance@apexdigital.io',
        name: 'Marcus Vance',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        phone: '+1 (555) 674-8831',
        job_title: 'Senior Sales Director',
        role: 'sales_manager',
        workspace_id: DEFAULT_WORKSPACE_ID,
        created_at: new Date(Date.now() - 75 * 86400000).toISOString(),
      },
      {
        id: 'usr-mkt-04',
        email: 'elena.rostova@apexdigital.io',
        name: 'Elena Rostova',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
        phone: '+1 (555) 912-3344',
        job_title: 'Growth Marketing Lead',
        role: 'marketing_manager',
        workspace_id: DEFAULT_WORKSPACE_ID,
        created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
      },
      {
        id: 'usr-fin-05',
        email: 'david.kim@apexdigital.io',
        name: 'David Kim',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        phone: '+1 (555) 441-2098',
        job_title: 'Lead Financial Controller',
        role: 'accountant',
        workspace_id: DEFAULT_WORKSPACE_ID,
        created_at: new Date(Date.now() - 50 * 86400000).toISOString(),
      },
      {
        id: 'usr-support-06',
        email: 'maya.patel@apexdigital.io',
        name: 'Maya Patel',
        avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
        phone: '+1 (555) 883-9912',
        job_title: 'Client Success Manager',
        role: 'support_agent',
        workspace_id: DEFAULT_WORKSPACE_ID,
        created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
      }
    ];

    // 3. Contacts / Customers
    this.contacts = [
      {
        id: 'cnt-01',
        workspace_id: DEFAULT_WORKSPACE_ID,
        first_name: 'Jonathan',
        last_name: 'Hastings',
        email: 'j.hastings@solartide.com',
        phone: '+1 (415) 555-0192',
        job_title: 'VP of Engineering',
        company_name: 'SolarTide Energy',
        type: 'customer',
        total_spent: 34500,
        assigned_to: 'usr-sales-03',
        tags: ['Enterprise', 'Renewable Energy', 'High LTV'],
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
        address: '500 Howard St, San Francisco, CA 94105',
        created_at: new Date(Date.now() - 70 * 86400000).toISOString(),
        updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
      {
        id: 'cnt-02',
        workspace_id: DEFAULT_WORKSPACE_ID,
        first_name: 'Clara',
        last_name: 'Bellingham',
        email: 'clara@novabiotech.io',
        phone: '+1 (617) 555-8832',
        job_title: 'Chief Operating Officer',
        company_name: 'Nova BioTech',
        type: 'customer',
        total_spent: 18200,
        assigned_to: 'usr-sales-03',
        tags: ['Healthcare', 'Retainer Client'],
        avatar: 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=150&auto=format&fit=crop&q=80',
        address: '100 Binney St, Cambridge, MA 02142',
        created_at: new Date(Date.now() - 65 * 86400000).toISOString(),
        updated_at: new Date(Date.now() - 5 * 86400000).toISOString(),
      },
      {
        id: 'cnt-03',
        workspace_id: DEFAULT_WORKSPACE_ID,
        first_name: 'Robert',
        last_name: 'Langdon',
        email: 'robert@symbiontlogistics.com',
        phone: '+1 (312) 555-7711',
        job_title: 'Director of Procurement',
        company_name: 'Symbiont Logistics',
        type: 'customer',
        total_spent: 12400,
        assigned_to: 'usr-sales-03',
        tags: ['Supply Chain', 'Net 30'],
        avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
        address: '222 N LaSalle St, Chicago, IL 60601',
        created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
        updated_at: new Date(Date.now() - 10 * 86400000).toISOString(),
      },
      {
        id: 'cnt-04',
        workspace_id: DEFAULT_WORKSPACE_ID,
        first_name: 'Sophia',
        last_name: 'Montenegro',
        email: 'sophia@aeroflux.design',
        phone: '+1 (206) 555-3490',
        job_title: 'Managing Partner',
        company_name: 'Aeroflux Studio',
        type: 'customer',
        total_spent: 8900,
        assigned_to: 'usr-owner-01',
        tags: ['Design Agency', 'Fast Pay'],
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        address: '1201 3rd Ave, Seattle, WA 98101',
        created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
        updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
      },
      {
        id: 'cnt-05',
        workspace_id: DEFAULT_WORKSPACE_ID,
        first_name: 'Devon',
        last_name: 'Archer',
        email: 'devon@horizoncloud.tech',
        phone: '+1 (512) 555-9023',
        job_title: 'Infrastructure Architect',
        company_name: 'Horizon Cloud Tech',
        type: 'lead',
        total_spent: 0,
        assigned_to: 'usr-sales-03',
        tags: ['Warm Lead', 'Cloud Migration'],
        avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
        created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
        updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
      }
    ];

    // 4. Leads
    this.leads = [
      {
        id: 'lead-01',
        workspace_id: DEFAULT_WORKSPACE_ID,
        first_name: 'Evelyn',
        last_name: 'Vance',
        company: 'OmniGrid Networks',
        email: 'e.vance@omnigrid.com',
        phone: '+1 (415) 555-7832',
        status: 'qualified',
        source: 'website_form',
        score: 85,
        estimated_value: 28000,
        notes: 'Inquired through main website form regarding custom enterprise workflow automation setup.',
        tags: ['Enterprise', 'High Priority', 'Form Lead'],
        assigned_to: 'usr-sales-03',
        last_contacted_at: new Date(Date.now() - 1 * 86400000).toISOString(),
        created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
        updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
      },
      {
        id: 'lead-02',
        workspace_id: DEFAULT_WORKSPACE_ID,
        first_name: 'Liam',
        last_name: 'Gallagher',
        company: 'Starlight Media Group',
        email: 'liam@starlightmedia.co',
        phone: '+1 (212) 555-9011',
        status: 'new',
        source: 'campaign',
        campaign_id: 'cmp-01',
        score: 70,
        estimated_value: 15000,
        notes: 'Downloaded Q3 Growth Whitepaper from paid inbound campaign.',
        tags: ['Inbound', 'Media'],
        assigned_to: 'usr-sales-03',
        created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
        updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
      {
        id: 'lead-03',
        workspace_id: DEFAULT_WORKSPACE_ID,
        first_name: 'Maya',
        last_name: 'Lin',
        company: 'Veritas Financial Advisory',
        email: 'mlin@veritasadvisory.com',
        phone: '+1 (617) 555-3342',
        status: 'proposal_sent',
        source: 'referral',
        score: 92,
        estimated_value: 42000,
        notes: 'Referred by Jonathan Hastings. Sent full proposal on Monday.',
        tags: ['Referral', 'VIP', 'High Value'],
        assigned_to: 'usr-owner-01',
        last_contacted_at: new Date(Date.now() - 3 * 86400000).toISOString(),
        created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
        updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
      },
      {
        id: 'lead-04',
        workspace_id: DEFAULT_WORKSPACE_ID,
        first_name: 'Brian',
        last_name: 'O\'Connor',
        company: 'Apex Fasteners Corp',
        email: 'brian@apexfasteners.com',
        phone: '+1 (313) 555-9988',
        status: 'contacted',
        source: 'cold_outreach',
        score: 45,
        estimated_value: 9500,
        notes: 'Had introductory 15-minute call. Scheduling technical audit demo next week.',
        tags: ['Manufacturing', 'Mid-Market'],
        assigned_to: 'usr-sales-03',
        last_contacted_at: new Date(Date.now() - 4 * 86400000).toISOString(),
        created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
        updated_at: new Date(Date.now() - 4 * 86400000).toISOString(),
      },
      {
        id: 'lead-05',
        workspace_id: DEFAULT_WORKSPACE_ID,
        first_name: 'Tanya',
        last_name: 'Kowalski',
        company: 'GreenLeaf Organics',
        email: 'tanya@greenleaforganics.org',
        phone: '+1 (503) 555-1284',
        status: 'negotiating',
        source: 'event',
        score: 88,
        estimated_value: 19500,
        notes: 'Met at NYC Tech Summit. Finalizing contract terms and payment schedule.',
        tags: ['Sustainability', 'Summit Lead'],
        assigned_to: 'usr-sales-03',
        last_contacted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
        created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
        updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
      }
    ];

    // 5. Deals
    this.deals = [
      {
        id: 'deal-01',
        workspace_id: DEFAULT_WORKSPACE_ID,
        title: 'Veritas Advisory - Custom Business OS Architecture',
        value: 42000,
        stage: 'proposal_sent',
        probability: 75,
        expected_close_date: new Date(Date.now() + 10 * 86400000).toISOString().split('T')[0],
        contact_id: 'cnt-01',
        assigned_to: 'usr-owner-01',
        tags: ['High Value', 'Consulting'],
        notes: 'Comprehensive CRM & automation overhaul across 4 branches.',
        created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
        updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
      },
      {
        id: 'deal-02',
        workspace_id: DEFAULT_WORKSPACE_ID,
        title: 'OmniGrid Networks - Enterprise Growth Retainer',
        value: 28000,
        stage: 'qualification',
        probability: 50,
        expected_close_date: new Date(Date.now() + 20 * 86400000).toISOString().split('T')[0],
        assigned_to: 'usr-sales-03',
        tags: ['Retainer', 'Quarterly'],
        notes: 'Discovery call completed; drafting scope of work.',
        created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
        updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
      {
        id: 'deal-03',
        workspace_id: DEFAULT_WORKSPACE_ID,
        title: 'GreenLeaf Organics - Multi-Channel Operations System',
        value: 19500,
        stage: 'negotiation',
        probability: 90,
        expected_close_date: new Date(Date.now() + 5 * 86400000).toISOString().split('T')[0],
        assigned_to: 'usr-sales-03',
        tags: ['Ready to Sign', 'Automation'],
        notes: 'Legal review passed; awaiting CFO signature.',
        created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
        updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
      {
        id: 'deal-04',
        workspace_id: DEFAULT_WORKSPACE_ID,
        title: 'SolarTide Energy - Annual System Expansion',
        value: 34500,
        stage: 'closed_won',
        probability: 100,
        expected_close_date: new Date(Date.now() - 15 * 86400000).toISOString().split('T')[0],
        contact_id: 'cnt-01',
        assigned_to: 'usr-sales-03',
        tags: ['Renewed', 'VIP'],
        notes: 'Successfully closed and invoiced.',
        created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
        updated_at: new Date(Date.now() - 15 * 86400000).toISOString(),
      },
      {
        id: 'deal-05',
        workspace_id: DEFAULT_WORKSPACE_ID,
        title: 'Nova BioTech - Compliance & Communication Hub',
        value: 18200,
        stage: 'closed_won',
        probability: 100,
        expected_close_date: new Date(Date.now() - 30 * 86400000).toISOString().split('T')[0],
        contact_id: 'cnt-02',
        assigned_to: 'usr-sales-03',
        tags: ['Delivered', 'Healthcare'],
        created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
        updated_at: new Date(Date.now() - 30 * 86400000).toISOString(),
      },
      {
        id: 'deal-06',
        workspace_id: DEFAULT_WORKSPACE_ID,
        title: 'Starlight Media - Inbound Pipeline Acceleration',
        value: 15000,
        stage: 'discovery',
        probability: 25,
        expected_close_date: new Date(Date.now() + 35 * 86400000).toISOString().split('T')[0],
        assigned_to: 'usr-sales-03',
        tags: ['Early Stage'],
        created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
        updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
      }
    ];

    // 6. Products & Services
    this.productsServices = [
      {
        id: 'prod-01',
        workspace_id: DEFAULT_WORKSPACE_ID,
        name: 'Enterprise Business OS Setup & Deployment',
        sku: 'SRV-BOS-ENT',
        type: 'service',
        price: 15000,
        cost: 3500,
        tax_rate: 8.875,
        billing_period: 'one_off',
        description: 'Complete configuration of CRM, custom pipelines, customer inbox, appointment routing, and automated billing.',
        category: 'Implementation',
        active: true,
        created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
      },
      {
        id: 'prod-02',
        workspace_id: DEFAULT_WORKSPACE_ID,
        name: 'Monthly Growth & AI Automation Retainer',
        sku: 'SRV-RET-MO',
        type: 'service',
        price: 3500,
        cost: 600,
        tax_rate: 8.875,
        billing_period: 'monthly',
        description: 'Continuous workflow optimization, custom AI assistants, automated outreach, and quarterly growth reviews.',
        category: 'Retainers',
        active: true,
        created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
      },
      {
        id: 'prod-03',
        workspace_id: DEFAULT_WORKSPACE_ID,
        name: 'Custom Pipeline & API Integration Sprint',
        sku: 'SRV-INT-SPR',
        type: 'service',
        price: 6500,
        cost: 1200,
        tax_rate: 8.875,
        billing_period: 'one_off',
        description: 'Dedicated 2-week engineering sprint for ERP, custom webhooks, payment gateways, and data migrations.',
        category: 'Engineering',
        active: true,
        created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
      },
      {
        id: 'prod-04',
        workspace_id: DEFAULT_WORKSPACE_ID,
        name: 'Omnichannel Support Desk Configuration',
        sku: 'SRV-DESK-CFG',
        type: 'service',
        price: 4200,
        cost: 800,
        tax_rate: 8.875,
        billing_period: 'one_off',
        description: 'WhatsApp Business API, Web Chat widgets, canned response library, and automated escalation triggers.',
        category: 'Support',
        active: true,
        created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
      },
      {
        id: 'prod-05',
        workspace_id: DEFAULT_WORKSPACE_ID,
        name: 'Executive Strategy & Revenue Architecture Audit',
        sku: 'SRV-AUDIT-STRAT',
        type: 'service',
        price: 2500,
        cost: 300,
        tax_rate: 8.875,
        billing_period: 'one_off',
        description: 'Comprehensive 360-degree audit of sales velocity, CAC, churn risk, and operational bottleneck resolution.',
        category: 'Consulting',
        active: true,
        created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
      }
    ];

    // 7. Invoices & Quotes
    this.invoices = [
      {
        id: 'inv-01',
        workspace_id: DEFAULT_WORKSPACE_ID,
        invoice_number: 'INV-2026-001',
        contact_id: 'cnt-01',
        contact_name: 'Jonathan Hastings (SolarTide Energy)',
        contact_email: 'j.hastings@solartide.com',
        status: 'paid',
        issue_date: new Date(Date.now() - 40 * 86400000).toISOString().split('T')[0],
        due_date: new Date(Date.now() - 10 * 86400000).toISOString().split('T')[0],
        line_items: [
          {
            id: 'li-01',
            product_id: 'prod-01',
            description: 'Enterprise Business OS Setup & Deployment',
            quantity: 1,
            unit_price: 15000,
            tax_rate: 8.875,
            total: 15000,
          },
          {
            id: 'li-02',
            product_id: 'prod-02',
            description: 'Monthly Growth & AI Automation Retainer (Month 1)',
            quantity: 1,
            unit_price: 3500,
            tax_rate: 8.875,
            total: 3500,
          }
        ],
        subtotal: 18500,
        tax_amount: 1641.88,
        discount_amount: 0,
        total: 20141.88,
        paid_amount: 20141.88,
        currency: 'USD',
        payment_method: 'stripe',
        paid_at: new Date(Date.now() - 32 * 86400000).toISOString(),
        notes: 'Thank you for your partnership! SolarTide deployment completed.',
        created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
      },
      {
        id: 'inv-02',
        workspace_id: DEFAULT_WORKSPACE_ID,
        invoice_number: 'INV-2026-002',
        contact_id: 'cnt-02',
        contact_name: 'Clara Bellingham (Nova BioTech)',
        contact_email: 'clara@novabiotech.io',
        status: 'paid',
        issue_date: new Date(Date.now() - 30 * 86400000).toISOString().split('T')[0],
        due_date: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
        line_items: [
          {
            id: 'li-03',
            product_id: 'prod-01',
            description: 'Enterprise Business OS Setup & Deployment',
            quantity: 1,
            unit_price: 15000,
            tax_rate: 8.875,
            total: 15000,
          }
        ],
        subtotal: 15000,
        tax_amount: 1331.25,
        discount_amount: 500,
        total: 15831.25,
        paid_amount: 15831.25,
        currency: 'USD',
        payment_method: 'bank_transfer',
        paid_at: new Date(Date.now() - 12 * 86400000).toISOString(),
        created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
      },
      {
        id: 'inv-03',
        workspace_id: DEFAULT_WORKSPACE_ID,
        invoice_number: 'INV-2026-003',
        contact_id: 'cnt-03',
        contact_name: 'Robert Langdon (Symbiont Logistics)',
        contact_email: 'robert@symbiontlogistics.com',
        status: 'overdue',
        issue_date: new Date(Date.now() - 35 * 86400000).toISOString().split('T')[0],
        due_date: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
        line_items: [
          {
            id: 'li-04',
            product_id: 'prod-03',
            description: 'Custom Pipeline & API Integration Sprint',
            quantity: 1,
            unit_price: 6500,
            tax_rate: 8.875,
            total: 6500,
          },
          {
            id: 'li-05',
            product_id: 'prod-04',
            description: 'Omnichannel Support Desk Configuration',
            quantity: 1,
            unit_price: 4200,
            tax_rate: 8.875,
            total: 4200,
          }
        ],
        subtotal: 10700,
        tax_amount: 949.63,
        discount_amount: 0,
        total: 11649.63,
        paid_amount: 0,
        currency: 'USD',
        notes: 'Overdue reminder notice sent on Aug 15. Follow up with Robert directly.',
        created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
      },
      {
        id: 'inv-04',
        workspace_id: DEFAULT_WORKSPACE_ID,
        invoice_number: 'INV-2026-004',
        contact_id: 'cnt-04',
        contact_name: 'Sophia Montenegro (Aeroflux Studio)',
        contact_email: 'sophia@aeroflux.design',
        status: 'sent',
        issue_date: new Date(Date.now() - 6 * 86400000).toISOString().split('T')[0],
        due_date: new Date(Date.now() + 14 * 86400000).toISOString().split('T')[0],
        line_items: [
          {
            id: 'li-06',
            product_id: 'prod-02',
            description: 'Monthly Growth & AI Automation Retainer',
            quantity: 2,
            unit_price: 3500,
            tax_rate: 8.875,
            total: 7000,
          }
        ],
        subtotal: 7000,
        tax_amount: 621.25,
        discount_amount: 0,
        total: 7621.25,
        paid_amount: 0,
        currency: 'USD',
        created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
      },
      {
        id: 'inv-05',
        workspace_id: DEFAULT_WORKSPACE_ID,
        invoice_number: 'INV-2026-005',
        contact_id: 'cnt-01',
        contact_name: 'Jonathan Hastings (SolarTide Energy)',
        contact_email: 'j.hastings@solartide.com',
        status: 'draft',
        issue_date: new Date().toISOString().split('T')[0],
        due_date: new Date(Date.now() + 30 * 86400000).toISOString().split('T')[0],
        line_items: [
          {
            id: 'li-07',
            product_id: 'prod-02',
            description: 'Monthly Growth & AI Automation Retainer (Month 2)',
            quantity: 1,
            unit_price: 3500,
            tax_rate: 8.875,
            total: 3500,
          }
        ],
        subtotal: 3500,
        tax_amount: 310.63,
        discount_amount: 0,
        total: 3810.63,
        paid_amount: 0,
        currency: 'USD',
        created_at: new Date().toISOString(),
      }
    ];

    this.quotes = [
      {
        id: 'qte-01',
        workspace_id: DEFAULT_WORKSPACE_ID,
        quote_number: 'QTE-2026-101',
        contact_id: 'cnt-01',
        contact_name: 'Jonathan Hastings',
        contact_email: 'j.hastings@solartide.com',
        status: 'accepted',
        issue_date: new Date(Date.now() - 45 * 86400000).toISOString().split('T')[0],
        expiry_date: new Date(Date.now() - 15 * 86400000).toISOString().split('T')[0],
        line_items: [
          {
            id: 'qli-01',
            description: 'Enterprise Business OS Setup & Deployment',
            quantity: 1,
            unit_price: 15000,
            tax_rate: 8.875,
            total: 15000,
          }
        ],
        subtotal: 15000,
        tax_amount: 1331.25,
        discount_amount: 0,
        total: 16331.25,
        converted_invoice_id: 'inv-01',
        created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
      },
      {
        id: 'qte-02',
        workspace_id: DEFAULT_WORKSPACE_ID,
        quote_number: 'QTE-2026-102',
        contact_id: 'cnt-05',
        contact_name: 'Devon Archer',
        contact_email: 'devon@horizoncloud.tech',
        status: 'sent',
        issue_date: new Date(Date.now() - 4 * 86400000).toISOString().split('T')[0],
        expiry_date: new Date(Date.now() + 26 * 86400000).toISOString().split('T')[0],
        line_items: [
          {
            id: 'qli-02',
            description: 'Custom Pipeline & API Integration Sprint',
            quantity: 1,
            unit_price: 6500,
            tax_rate: 8.875,
            total: 6500,
          },
          {
            id: 'qli-03',
            description: 'Executive Strategy & Revenue Architecture Audit',
            quantity: 1,
            unit_price: 2500,
            tax_rate: 8.875,
            total: 2500,
          }
        ],
        subtotal: 9000,
        tax_amount: 798.75,
        discount_amount: 500,
        total: 9298.75,
        notes: 'Includes full technical architecture blueprint and 30-day post-launch warranty.',
        created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
      }
    ];

    // 8. Expenses
    this.expenses = [
      {
        id: 'exp-01',
        workspace_id: DEFAULT_WORKSPACE_ID,
        category: 'Software & Subscriptions',
        description: 'AWS Cloud Infrastructure & Database Hosting',
        amount: 840,
        date: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
        payment_method: 'Corporate Visa *8841',
        vendor: 'Amazon Web Services',
        tax_deductible: true,
        created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
      {
        id: 'exp-02',
        workspace_id: DEFAULT_WORKSPACE_ID,
        category: 'Marketing',
        description: 'Google Ads & Inbound Lead Acquisition Campaign',
        amount: 2200,
        date: new Date(Date.now() - 6 * 86400000).toISOString().split('T')[0],
        payment_method: 'Corporate Visa *8841',
        vendor: 'Google LLC',
        tax_deductible: true,
        created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
      },
      {
        id: 'exp-03',
        workspace_id: DEFAULT_WORKSPACE_ID,
        category: 'Office & Rent',
        description: 'WeWork Executive Studio Suite - Manhattan',
        amount: 3200,
        date: new Date(Date.now() - 15 * 86400000).toISOString().split('T')[0],
        payment_method: 'ACH Bank Wire',
        vendor: 'WeWork Companies LLC',
        tax_deductible: true,
        created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
      },
      {
        id: 'exp-04',
        workspace_id: DEFAULT_WORKSPACE_ID,
        category: 'Salaries & Contractors',
        description: 'Senior Frontend Engineering Contract Sprint',
        amount: 4500,
        date: new Date(Date.now() - 18 * 86400000).toISOString().split('T')[0],
        payment_method: 'Stripe Direct Pay',
        vendor: 'Apex Contracting Group',
        tax_deductible: true,
        created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
      },
      {
        id: 'exp-05',
        workspace_id: DEFAULT_WORKSPACE_ID,
        category: 'Travel & Entertainment',
        description: 'Client Dinner with SolarTide & Veritas Stakeholders',
        amount: 460,
        date: new Date(Date.now() - 22 * 86400000).toISOString().split('T')[0],
        payment_method: 'Amex Business *4012',
        vendor: 'Gramercy Tavern NY',
        tax_deductible: true,
        created_at: new Date(Date.now() - 22 * 86400000).toISOString(),
      }
    ];

    // 9. Marketing Campaigns, Lead Forms, Coupons
    this.campaigns = [
      {
        id: 'cmp-01',
        workspace_id: DEFAULT_WORKSPACE_ID,
        name: 'Q3 Enterprise Lead Gen Accelerator',
        type: 'lead_gen',
        status: 'active',
        objective: 'Generate 40+ qualified B2B leads for the Enterprise Business OS tier.',
        budget: 5000,
        actual_spend: 3100,
        start_date: new Date(Date.now() - 30 * 86400000).toISOString().split('T')[0],
        end_date: new Date(Date.now() + 30 * 86400000).toISOString().split('T')[0],
        target_audience: 'VP of Tech, COOs, and Founders of 20-200 employee firms in US & Canada.',
        utm_campaign: 'q3_growth_2026',
        utm_source: 'google_search',
        utm_medium: 'cpc',
        leads_generated: 28,
        conversions_count: 6,
        pipeline_value_generated: 114000,
        roi_percentage: 3577,
        created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
      },
      {
        id: 'cmp-02',
        workspace_id: DEFAULT_WORKSPACE_ID,
        name: 'Webinar: Scaling SMB Operations with AI Automations',
        type: 'webinar',
        status: 'active',
        objective: 'Host live workshop demonstrating workflow simplification & appointment bookings.',
        budget: 1500,
        actual_spend: 950,
        start_date: new Date(Date.now() - 10 * 86400000).toISOString().split('T')[0],
        end_date: new Date(Date.now() + 15 * 86400000).toISOString().split('T')[0],
        target_audience: 'Agency Owners, Professional Services Founders, Legal & Accounting partners.',
        utm_campaign: 'webinar_ai_ops',
        utm_source: 'newsletter',
        utm_medium: 'email',
        leads_generated: 45,
        conversions_count: 8,
        pipeline_value_generated: 52000,
        roi_percentage: 5373,
        created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
      },
      {
        id: 'cmp-03',
        workspace_id: DEFAULT_WORKSPACE_ID,
        name: 'Client Referral Program: Q3 Bonus',
        type: 'referral',
        status: 'active',
        objective: 'Incentivize existing high-LTV customers to introduce peer founders.',
        budget: 2000,
        actual_spend: 800,
        start_date: new Date(Date.now() - 20 * 86400000).toISOString().split('T')[0],
        target_audience: 'Existing customers with >$10k spend.',
        utm_campaign: 'referral_vip_2026',
        utm_source: 'client_portal',
        utm_medium: 'direct',
        leads_generated: 7,
        conversions_count: 3,
        pipeline_value_generated: 84000,
        roi_percentage: 10400,
        created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
      }
    ];

    this.leadForms = [
      {
        id: 'frm-01',
        workspace_id: DEFAULT_WORKSPACE_ID,
        title: 'Executive Growth & Strategy Consultation Inquiry',
        description: 'Schedule an executive discovery consultation to audit and modernize your business systems.',
        campaign_id: 'cmp-01',
        submit_button_text: 'Request Strategy Session',
        success_message: 'Thank you! A senior business architect from our team will review your inquiry and reach out within 2 hours.',
        redirect_url: '',
        fields: [
          { id: 'f1', label: 'Full Name', type: 'text', placeholder: 'e.g. John Doe', required: true },
          { id: 'f2', label: 'Business Email', type: 'email', placeholder: 'john@yourcompany.com', required: true },
          { id: 'f3', label: 'Phone Number', type: 'phone', placeholder: '+1 (555) 000-0000', required: false },
          { id: 'f4', label: 'Company Name', type: 'text', placeholder: 'Acme Corp', required: true },
          { id: 'f5', label: 'Current Team Size', type: 'select', required: true, options: ['1-10 employees', '11-50 employees', '51-200 employees', '200+ employees'] },
          { id: 'f6', label: 'Primary Operational Challenge', type: 'textarea', placeholder: 'Tell us what systems or bottlenecks you want to resolve...', required: true }
        ],
        embed_code: '<iframe src="/public/embed/form/frm-01" width="100%" height="520" frameborder="0"></iframe>',
        submissions_count: 32,
        active: true,
        created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
      },
      {
        id: 'frm-02',
        workspace_id: DEFAULT_WORKSPACE_ID,
        title: 'Quick Contact & Quote Request Form',
        description: 'Get a tailored pricing quotation for software setup and automation retainers.',
        submit_button_text: 'Get Instant Estimate',
        success_message: 'Inquiry received! We have generated your preliminary quote and emailed it to your inbox.',
        fields: [
          { id: 'f1', label: 'Contact Name', type: 'text', placeholder: 'Jane Smith', required: true },
          { id: 'f2', label: 'Email Address', type: 'email', placeholder: 'jane@enterprise.org', required: true },
          { id: 'f3', label: 'Services Interested In', type: 'select', required: true, options: ['Full Business OS Setup', 'Monthly Automation Retainer', 'Custom API Sprint', 'Omnichannel Inbox Desk'] }
        ],
        embed_code: '<iframe src="/public/embed/form/frm-02" width="100%" height="400" frameborder="0"></iframe>',
        submissions_count: 19,
        active: true,
        created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
      }
    ];

    this.coupons = [
      {
        id: 'cpn-01',
        workspace_id: DEFAULT_WORKSPACE_ID,
        code: 'GROWTH2026',
        description: '15% off onboarding implementation fee for new annual retainers.',
        discount_type: 'percentage',
        discount_value: 15,
        min_spend: 5000,
        max_uses: 20,
        used_count: 7,
        expires_at: new Date(Date.now() + 60 * 86400000).toISOString(),
        active: true,
        created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
      },
      {
        id: 'cpn-02',
        workspace_id: DEFAULT_WORKSPACE_ID,
        code: 'SUMMITVIP',
        description: '$1,000 flat discount for NYC Tech Summit attendees.',
        discount_type: 'fixed_amount',
        discount_value: 1000,
        min_spend: 10000,
        max_uses: 10,
        used_count: 3,
        expires_at: new Date(Date.now() + 15 * 86400000).toISOString(),
        active: true,
        created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
      }
    ];

    // 10. Unified Inbox: Conversations & Messages
    this.conversations = [
      {
        id: 'cnv-01',
        workspace_id: DEFAULT_WORKSPACE_ID,
        channel: 'email',
        contact_id: 'cnt-01',
        contact_name: 'Jonathan Hastings',
        contact_email: 'j.hastings@solartide.com',
        subject: 'Re: Q4 Expansion Roadmap & Additional Seats',
        assigned_to: 'usr-sales-03',
        assigned_to_name: 'Marcus Vance',
        status: 'open',
        priority: 'high',
        tags: ['VIP', 'Expansion', 'SolarTide'],
        unread_count: 1,
        last_message_text: 'Hi Marcus, the team tested the new automation flows and they look fantastic. Can we add 15 more user accounts before Friday?',
        last_message_at: new Date(Date.now() - 25 * 60000).toISOString(),
        created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
      },
      {
        id: 'cnv-02',
        workspace_id: DEFAULT_WORKSPACE_ID,
        channel: 'whatsapp',
        contact_id: 'cnt-02',
        contact_name: 'Clara Bellingham',
        contact_phone: '+1 (617) 555-8832',
        subject: 'WhatsApp Inquiry from Nova BioTech',
        assigned_to: 'usr-support-06',
        assigned_to_name: 'Maya Patel',
        status: 'open',
        priority: 'medium',
        tags: ['WhatsApp', 'Support'],
        unread_count: 2,
        last_message_text: 'Hello Maya! Quick question: is there a way to export our quarterly appointment history to CSV for our compliance board?',
        last_message_at: new Date(Date.now() - 2 * 3600000).toISOString(),
        created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
      },
      {
        id: 'cnv-03',
        workspace_id: DEFAULT_WORKSPACE_ID,
        channel: 'web_chat',
        contact_name: 'Devon Archer',
        contact_email: 'devon@horizoncloud.tech',
        subject: 'Live Website Chat regarding API Integration',
        assigned_to: 'usr-sales-03',
        assigned_to_name: 'Marcus Vance',
        status: 'pending',
        priority: 'high',
        tags: ['Website Lead', 'Inbound'],
        unread_count: 0,
        last_message_text: 'Thanks for sending over the technical spec, Marcus. I will review it with our Lead Architect tomorrow morning.',
        last_message_at: new Date(Date.now() - 18 * 3600000).toISOString(),
        created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
      },
      {
        id: 'cnv-04',
        workspace_id: DEFAULT_WORKSPACE_ID,
        channel: 'email',
        contact_id: 'cnt-03',
        contact_name: 'Robert Langdon',
        contact_email: 'robert@symbiontlogistics.com',
        subject: 'Follow-up on Invoice INV-2026-003',
        assigned_to: 'usr-fin-05',
        assigned_to_name: 'David Kim',
        status: 'open',
        priority: 'high',
        tags: ['Overdue Invoice', 'Finance'],
        unread_count: 1,
        last_message_text: 'Hi David, apologies for the slight delay. Our accounts payable department had a system migration this week. Wire will clear by Wednesday.',
        last_message_at: new Date(Date.now() - 28 * 3600000).toISOString(),
        created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
      }
    ];

    this.messages = [
      {
        id: 'msg-01',
        conversation_id: 'cnv-01',
        sender_type: 'customer',
        sender_name: 'Jonathan Hastings',
        content: 'Hi Marcus, the team tested the new automation flows and they look fantastic. Can we add 15 more user accounts before Friday?',
        created_at: new Date(Date.now() - 25 * 60000).toISOString(),
      },
      {
        id: 'msg-02',
        conversation_id: 'cnv-02',
        sender_type: 'customer',
        sender_name: 'Clara Bellingham',
        content: 'Hello Maya! Quick question: is there a way to export our quarterly appointment history to CSV for our compliance board?',
        created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
      },
      {
        id: 'msg-03',
        conversation_id: 'cnv-03',
        sender_type: 'agent',
        sender_name: 'Marcus Vance',
        content: 'Hey Devon! Here is our comprehensive API documentation and architecture overview. Let me know if you want to hop on a 15-minute screen share.',
        created_at: new Date(Date.now() - 20 * 3600000).toISOString(),
      },
      {
        id: 'msg-04',
        conversation_id: 'cnv-03',
        sender_type: 'customer',
        sender_name: 'Devon Archer',
        content: 'Thanks for sending over the technical spec, Marcus. I will review it with our Lead Architect tomorrow morning.',
        created_at: new Date(Date.now() - 18 * 3600000).toISOString(),
      }
    ];

    // 11. Appointment Types & Appointments
    this.appointmentTypes = [
      {
        id: 'apt-type-01',
        workspace_id: DEFAULT_WORKSPACE_ID,
        name: 'Executive Business Strategy Consultation',
        slug: 'executive-strategy',
        description: 'Comprehensive 45-minute deep dive with a Senior Business Architect to evaluate pipeline bottlenecks and growth opportunities.',
        duration_minutes: 45,
        price: 250,
        currency: 'USD',
        location_type: 'video_call',
        location_details: 'https://meet.google.com/nexus-exec-strat',
        staff_ids: ['usr-owner-01', 'usr-sales-03'],
        buffer_before_minutes: 5,
        buffer_after_minutes: 15,
        color: '#2563EB',
        active: true,
        created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
      },
      {
        id: 'apt-type-02',
        workspace_id: DEFAULT_WORKSPACE_ID,
        name: 'Product Demo & Workflow Walkthrough',
        slug: 'product-demo',
        description: '30-minute personalized demonstration of NexusOS CRM, Invoicing, and Visual Automation Engine tailored for your team.',
        duration_minutes: 30,
        price: 0,
        currency: 'USD',
        location_type: 'video_call',
        location_details: 'https://meet.google.com/nexus-product-demo',
        staff_ids: ['usr-sales-03'],
        buffer_before_minutes: 0,
        buffer_after_minutes: 10,
        color: '#10B981',
        active: true,
        created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
      },
      {
        id: 'apt-type-03',
        workspace_id: DEFAULT_WORKSPACE_ID,
        name: 'VIP Client Quarterly Account Review',
        slug: 'quarterly-review',
        description: '60-minute executive retrospective on quarterly metrics, ROI, and upcoming roadmap milestones.',
        duration_minutes: 60,
        price: 0,
        currency: 'USD',
        location_type: 'video_call',
        location_details: 'https://meet.google.com/nexus-vip-review',
        staff_ids: ['usr-owner-01', 'usr-admin-02'],
        buffer_before_minutes: 10,
        buffer_after_minutes: 20,
        color: '#8B5CF6',
        active: true,
        created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
      }
    ];

    const today = new Date();
    this.appointments = [
      {
        id: 'apt-01',
        workspace_id: DEFAULT_WORKSPACE_ID,
        appointment_type_id: 'apt-type-02',
        appointment_type_name: 'Product Demo & Workflow Walkthrough',
        customer_name: 'Liam Gallagher',
        customer_email: 'liam@starlightmedia.co',
        customer_phone: '+1 (212) 555-9011',
        staff_id: 'usr-sales-03',
        staff_name: 'Marcus Vance',
        start_time: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 11, 0).toISOString(),
        end_time: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 11, 30).toISOString(),
        status: 'confirmed',
        location: 'Google Meet Video Call',
        meeting_url: 'https://meet.google.com/nex-demo-2026',
        notes: 'Interested in replacing HubSpot and Calendly with one single operating system.',
        created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
      {
        id: 'apt-02',
        workspace_id: DEFAULT_WORKSPACE_ID,
        appointment_type_id: 'apt-type-01',
        appointment_type_name: 'Executive Business Strategy Consultation',
        customer_name: 'Evelyn Vance',
        customer_email: 'e.vance@omnigrid.com',
        customer_phone: '+1 (415) 555-7832',
        staff_id: 'usr-owner-01',
        staff_name: 'Alex Rivera',
        start_time: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 1, 14, 0).toISOString(),
        end_time: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 1, 14, 45).toISOString(),
        status: 'confirmed',
        location: 'Google Meet Video Call',
        meeting_url: 'https://meet.google.com/nex-exec-strat',
        notes: 'Preparing custom architecture deck for multi-tenant deployment.',
        created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
      },
      {
        id: 'apt-03',
        workspace_id: DEFAULT_WORKSPACE_ID,
        appointment_type_id: 'apt-type-03',
        appointment_type_name: 'VIP Client Quarterly Account Review',
        customer_name: 'Jonathan Hastings',
        customer_email: 'j.hastings@solartide.com',
        contact_id: 'cnt-01',
        staff_id: 'usr-owner-01',
        staff_name: 'Alex Rivera',
        start_time: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 3, 15, 30).toISOString(),
        end_time: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 3, 16, 30).toISOString(),
        status: 'confirmed',
        location: 'Google Meet Video Call',
        meeting_url: 'https://meet.google.com/nex-vip-review',
        notes: 'Reviewing Q3 cost savings of $42,000 achieved through automated workflows.',
        created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
      },
      {
        id: 'apt-04',
        workspace_id: DEFAULT_WORKSPACE_ID,
        appointment_type_id: 'apt-type-02',
        appointment_type_name: 'Product Demo & Workflow Walkthrough',
        customer_name: 'Brian O\'Connor',
        customer_email: 'brian@apexfasteners.com',
        staff_id: 'usr-sales-03',
        staff_name: 'Marcus Vance',
        start_time: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 3, 10, 0).toISOString(),
        end_time: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 3, 10, 30).toISOString(),
        status: 'completed',
        location: 'Google Meet Video Call',
        meeting_url: 'https://meet.google.com/nex-demo-walkthru',
        notes: 'Demo went great. Sent follow up summary email.',
        created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
      }
    ];

    // 12. Automation Workflows & Logs
    this.automations = [
      {
        id: 'auto-01',
        workspace_id: DEFAULT_WORKSPACE_ID,
        name: 'Auto-Qualify & Route Inbound Website Leads',
        description: 'When a new lead is submitted from website forms, automatically calculate lead score, assign to senior sales director, and send an email notification.',
        trigger: {
          type: 'new_lead_created',
          config: { source: 'website_form' }
        },
        conditions: [
          { field: 'score', operator: 'greater_than', value: '50' }
        ],
        actions: [
          {
            id: 'act-01',
            type: 'assign_team_member',
            config: { staff_id: 'usr-sales-03', staff_name: 'Marcus Vance' }
          },
          {
            id: 'act-02',
            type: 'send_email_notification',
            config: { template: 'lead_welcome', recipient: '{{lead.email}}' }
          },
          {
            id: 'act-03',
            type: 'create_task',
            config: { title: 'First Touch Call with {{lead.first_name}} {{lead.last_name}}', priority: 'high', due_hours: 4 }
          }
        ],
        is_active: true,
        execution_count: 84,
        last_executed_at: new Date(Date.now() - 2 * 3600000).toISOString(),
        created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
      },
      {
        id: 'auto-02',
        workspace_id: DEFAULT_WORKSPACE_ID,
        name: 'Automated Overdue Invoice Recovery & Dunning',
        description: 'When an invoice becomes overdue (>3 days), automatically create high-priority collection task, send automated reminder, and notify financial controller.',
        trigger: {
          type: 'invoice_overdue',
          config: { days_grace: 3 }
        },
        conditions: [],
        actions: [
          {
            id: 'act-04',
            type: 'send_email_notification',
            config: { template: 'invoice_dunning_friendly', recipient: '{{invoice.contact_email}}' }
          },
          {
            id: 'act-05',
            type: 'create_task',
            config: { title: 'Overdue Follow-up: {{invoice.invoice_number}}', priority: 'urgent', assigned_to: 'usr-fin-05' }
          }
        ],
        is_active: true,
        execution_count: 12,
        last_executed_at: new Date(Date.now() - 12 * 3600000).toISOString(),
        created_at: new Date(Date.now() - 50 * 86400000).toISOString(),
      },
      {
        id: 'auto-03',
        workspace_id: DEFAULT_WORKSPACE_ID,
        name: 'Appointment Confirmation & Calendar Sync',
        description: 'When an appointment is booked through public link, create CRM activity, send calendar invite, and schedule 24hr reminder.',
        trigger: {
          type: 'appointment_booked',
          config: {}
        },
        conditions: [],
        actions: [
          {
            id: 'act-06',
            type: 'send_appointment_reminder',
            config: { channel: 'email', send_before_hours: 24 }
          },
          {
            id: 'act-07',
            type: 'add_tag',
            config: { tag: 'Meeting Scheduled' }
          }
        ],
        is_active: true,
        execution_count: 57,
        last_executed_at: new Date(Date.now() - 5 * 3600000).toISOString(),
        created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
      },
      {
        id: 'auto-04',
        workspace_id: DEFAULT_WORKSPACE_ID,
        name: 'AI Deal Win Summarizer & Onboarding Trigger',
        description: 'When a deal moves to "Closed Won", generate automated AI onboarding scope and trigger customer creation.',
        trigger: {
          type: 'deal_stage_changed',
          config: { stage: 'closed_won' }
        },
        conditions: [],
        actions: [
          {
            id: 'act-08',
            type: 'run_ai_action',
            config: { prompt: 'Generate 30-day client onboarding checklist and email intro' }
          },
          {
            id: 'act-09',
            type: 'update_customer',
            config: { status: 'active_client' }
          }
        ],
        is_active: true,
        execution_count: 19,
        last_executed_at: new Date(Date.now() - 15 * 86400000).toISOString(),
        created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
      }
    ];

    this.automationLogs = [
      {
        id: 'log-01',
        workspace_id: DEFAULT_WORKSPACE_ID,
        automation_id: 'auto-01',
        automation_name: 'Auto-Qualify & Route Inbound Website Leads',
        trigger_event: 'new_lead_created (Evelyn Vance)',
        status: 'success',
        duration_ms: 142,
        actions_executed: 3,
        payload_summary: 'Assigned to Marcus Vance, Welcome Email Dispatched, Task Created.',
        created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
      },
      {
        id: 'log-02',
        workspace_id: DEFAULT_WORKSPACE_ID,
        automation_id: 'auto-03',
        automation_name: 'Appointment Confirmation & Calendar Sync',
        trigger_event: 'appointment_booked (Liam Gallagher - Product Demo)',
        status: 'success',
        duration_ms: 88,
        actions_executed: 2,
        payload_summary: 'Reminder queued for T-24h, Tag "Meeting Scheduled" appended to Contact.',
        created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
      },
      {
        id: 'log-03',
        workspace_id: DEFAULT_WORKSPACE_ID,
        automation_id: 'auto-02',
        automation_name: 'Automated Overdue Invoice Recovery & Dunning',
        trigger_event: 'invoice_overdue (INV-2026-003 - Symbiont Logistics)',
        status: 'success',
        duration_ms: 210,
        actions_executed: 2,
        payload_summary: 'Dunning reminder sent to robert@symbiontlogistics.com, Urgent Task assigned to David Kim.',
        created_at: new Date(Date.now() - 12 * 3600000).toISOString(),
      }
    ];

    // 13. Tasks
    this.tasks = [
      {
        id: 'tsk-01',
        workspace_id: DEFAULT_WORKSPACE_ID,
        title: 'Review Veritas Advisory proposal revisions with Alex',
        description: 'Confirm 4-branch multi-tenant architecture pricing and SLA terms before sending final contract.',
        assigned_to: 'usr-sales-03',
        due_date: new Date(Date.now() + 1 * 86400000).toISOString(),
        priority: 'high',
        status: 'in_progress',
        related_entity_type: 'deal',
        related_entity_id: 'deal-01',
        related_entity_name: 'Veritas Advisory Deal ($42,000)',
        created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
      {
        id: 'tsk-02',
        workspace_id: DEFAULT_WORKSPACE_ID,
        title: 'Prepare custom demo environment for Liam Gallagher (Starlight Media)',
        description: 'Set up sample video campaign metrics and mock CRM contacts for 11:00 AM demo.',
        assigned_to: 'usr-sales-03',
        due_date: new Date().toISOString(),
        priority: 'urgent',
        status: 'todo',
        related_entity_type: 'appointment',
        related_entity_id: 'apt-01',
        related_entity_name: 'Starlight Media Demo',
        created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
      },
      {
        id: 'tsk-03',
        workspace_id: DEFAULT_WORKSPACE_ID,
        title: 'Follow up with Robert Langdon on overdue wire clearance (INV-2026-003)',
        description: 'Verify ACH / wire confirmation with accounting department.',
        assigned_to: 'usr-fin-05',
        due_date: new Date(Date.now() + 2 * 86400000).toISOString(),
        priority: 'high',
        status: 'todo',
        related_entity_type: 'invoice',
        related_entity_id: 'inv-03',
        related_entity_name: 'INV-2026-003 ($11,649.63)',
        created_at: new Date(Date.now() - 12 * 3600000).toISOString(),
      },
      {
        id: 'tsk-04',
        workspace_id: DEFAULT_WORKSPACE_ID,
        title: 'Generate monthly executive growth report for Board of Directors',
        description: 'Compile CAC, LTV, revenue growth curve, and cash flow forecast.',
        assigned_to: 'usr-admin-02',
        due_date: new Date(Date.now() + 5 * 86400000).toISOString(),
        priority: 'medium',
        status: 'todo',
        created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
      }
    ];

    // 14. Activity Timeline
    this.activityTimeline = [
      {
        id: 'act-log-01',
        workspace_id: DEFAULT_WORKSPACE_ID,
        user_id: 'usr-sales-03',
        user_name: 'Marcus Vance',
        entity_type: 'lead',
        entity_id: 'lead-01',
        type: 'form_submission',
        title: 'New Lead Inquired via Website Form',
        description: 'Evelyn Vance from OmniGrid Networks submitted Strategy Consultation inquiry.',
        created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
      },
      {
        id: 'act-log-02',
        workspace_id: DEFAULT_WORKSPACE_ID,
        user_id: 'usr-sales-03',
        user_name: 'Marcus Vance',
        entity_type: 'deal',
        entity_id: 'deal-01',
        type: 'status_change',
        title: 'Deal Advanced to Proposal Sent',
        description: 'Proposal ($42,000) sent to Veritas Advisory committee.',
        created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
      },
      {
        id: 'act-log-03',
        workspace_id: DEFAULT_WORKSPACE_ID,
        user_id: 'usr-fin-05',
        user_name: 'David Kim',
        entity_type: 'invoice',
        entity_id: 'inv-01',
        type: 'payment',
        title: 'Invoice INV-2026-001 Paid in Full',
        description: 'SolarTide Energy paid $20,141.88 via Stripe processing.',
        created_at: new Date(Date.now() - 32 * 86400000).toISOString(),
      },
      {
        id: 'act-log-04',
        workspace_id: DEFAULT_WORKSPACE_ID,
        user_id: 'usr-owner-01',
        user_name: 'Alex Rivera',
        entity_type: 'appointment',
        entity_id: 'apt-01',
        type: 'meeting',
        title: 'Product Demo Booked by Liam Gallagher',
        description: 'Demo scheduled for today at 11:00 AM EST.',
        created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
      }
    ];

    // 15. Notifications
    this.notifications = [
      {
        id: 'notif-01',
        workspace_id: DEFAULT_WORKSPACE_ID,
        title: 'New High-Score Lead Assigned',
        message: 'Evelyn Vance (Score: 85) from OmniGrid Networks was assigned to your pipeline.',
        type: 'lead',
        link: '/crm/leads',
        is_read: false,
        created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
      },
      {
        id: 'notif-02',
        workspace_id: DEFAULT_WORKSPACE_ID,
        title: 'Overdue Invoice Alert',
        message: 'Invoice INV-2026-003 for Symbiont Logistics ($11,649.63) is 5 days overdue.',
        type: 'invoice',
        link: '/finance/invoices',
        is_read: false,
        created_at: new Date(Date.now() - 12 * 3600000).toISOString(),
      },
      {
        id: 'notif-03',
        workspace_id: DEFAULT_WORKSPACE_ID,
        title: 'Upcoming Appointment in 1 Hour',
        message: 'Product Demo & Workflow Walkthrough with Liam Gallagher starts at 11:00 AM.',
        type: 'appointment',
        link: '/appointments',
        is_read: false,
        created_at: new Date(Date.now() - 45 * 60000).toISOString(),
      },
      {
        id: 'notif-04',
        workspace_id: DEFAULT_WORKSPACE_ID,
        title: 'Automation Workflow Executed',
        message: 'Auto-Qualify & Route Inbound Website Leads ran successfully.',
        type: 'automation',
        link: '/automations',
        is_read: true,
        created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
      }
    ];

    // 16. Audit Logs
    this.auditLogs = [
      {
        id: 'aud-01',
        workspace_id: DEFAULT_WORKSPACE_ID,
        user_id: 'usr-owner-01',
        user_name: 'Alex Rivera',
        action: 'UPDATE_SUBSCRIPTION_TIER',
        entity_type: 'workspace',
        entity_id: DEFAULT_WORKSPACE_ID,
        entity_title: 'Apex Digital Solutions',
        metadata: { previous: 'starter', new: 'professional', trigger: 'stripe_checkout_completed' },
        ip_address: '198.51.100.42',
        created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
      },
      {
        id: 'aud-02',
        workspace_id: DEFAULT_WORKSPACE_ID,
        user_id: 'usr-admin-02',
        user_name: 'Sarah Chen',
        action: 'INVITE_TEAM_MEMBER',
        entity_type: 'user',
        entity_id: 'usr-support-06',
        entity_title: 'Maya Patel (Support Agent)',
        metadata: { email: 'maya.patel@apexdigital.io', role: 'support_agent' },
        ip_address: '198.51.100.18',
        created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
      },
      {
        id: 'aud-03',
        workspace_id: DEFAULT_WORKSPACE_ID,
        user_id: 'usr-sales-03',
        user_name: 'Marcus Vance',
        action: 'GENERATE_INVOICE',
        entity_type: 'invoice',
        entity_id: 'inv-04',
        entity_title: 'INV-2026-004 ($7,621.25)',
        metadata: { contact: 'Sophia Montenegro', total: 7621.25 },
        ip_address: '198.51.100.99',
        created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
      }
    ];
  }
}

export const db = new InMemoryDatabase();
